begin;

create table if not exists public.security_events (
  id bigint generated by default as identity primary key,
  user_id text not null,event_type text not null,details jsonb not null default '{}'::jsonb,
  happened_at timestamptz not null default now()
);
alter table public.security_events enable row level security;
revoke all on public.security_events from public,anon,authenticated;
grant select on public.security_events to authenticated;

create or replace function public.lcb_app_user_id() returns text
language sql stable security definer set search_path=public as $$
  select case lower(coalesce(auth.jwt()->>'email',''))
    when '13726111370@163.com' then 'carol'
    when 'yanyi13411696203@163.com' then 'benson'
    else null
  end
  where exists (
    select 1 from auth.sessions s
    where s.id=(auth.jwt()->>'session_id')::uuid and s.user_id=auth.uid()
  )
$$;
revoke all on function public.lcb_app_user_id() from public,anon;
grant execute on function public.lcb_app_user_id() to authenticated;

create or replace function public.carol_personal_user() returns boolean
language sql stable security definer set search_path=public as $$
  select public.lcb_app_user_id() is not null
$$;
revoke all on function public.carol_personal_user() from public,anon;
grant execute on function public.carol_personal_user() to authenticated;

create or replace function public.lcb_matter_visible(payload jsonb) returns boolean
language sql stable security definer set search_path=public as $$
  select public.lcb_app_user_id()='carol'
    or payload->>'owner'=public.lcb_app_user_id()
    or coalesce(payload->'team','[]'::jsonb) ? public.lcb_app_user_id()
$$;
revoke all on function public.lcb_matter_visible(jsonb) from public,anon;
grant execute on function public.lcb_matter_visible(jsonb) to authenticated;

create or replace function public.lcb_protect_matter_access_fields() returns trigger
language plpgsql security definer set search_path=public as $$
declare uid text:=public.lcb_app_user_id();
begin
  if uid is null then raise exception 'unknown app user'; end if;
  if uid<>'carol' and old.data->>'owner'<>new.data->>'owner' then
    raise exception 'only Carol can transfer ownership';
  end if;
  if uid<>'carol' and uid<>old.data->>'owner'
    and old.data->'deletedAt' is distinct from new.data->'deletedAt' then
    raise exception 'only the owner can move a matter to or from trash';
  end if;
  if uid<>'carol' and uid<>old.data->>'owner' and old.data->'team' is distinct from new.data->'team' then
    raise exception 'only the owner can change members';
  end if;
  return new;
end $$;
drop trigger if exists lcb_protect_matter_access_fields on public.matters;
create trigger lcb_protect_matter_access_fields before update on public.matters
for each row execute function public.lcb_protect_matter_access_fields();

do $$ declare p record; begin
  for p in select schemaname,tablename,policyname from pg_policies
    where schemaname='public' and tablename in ('matters','logs','meta','lcb_public_keys','lcb_private_keys','lcb_matter_keys','security_events')
  loop execute format('drop policy if exists %I on %I.%I',p.policyname,p.schemaname,p.tablename); end loop;
end $$;

alter table public.matters enable row level security;
alter table public.logs enable row level security;
alter table public.meta enable row level security;
alter table public.lcb_public_keys enable row level security;
alter table public.lcb_private_keys enable row level security;
alter table public.lcb_matter_keys enable row level security;

create policy family_matters_select on public.matters for select to authenticated
using(public.lcb_matter_visible(data));
create policy family_matters_insert on public.matters for insert to authenticated
with check(public.lcb_app_user_id()='carol' or (
  data->>'owner'=public.lcb_app_user_id() and coalesce(data->'team','[]'::jsonb) ? public.lcb_app_user_id()
));
create policy family_matters_update on public.matters for update to authenticated
using(public.lcb_matter_visible(data)) with check(public.lcb_matter_visible(data));
create policy family_matters_delete on public.matters for delete to authenticated
using(public.lcb_app_user_id()='carol' or data->>'owner'=public.lcb_app_user_id());

create policy family_logs_select on public.logs for select to authenticated using(
  exists(select 1 from public.matters m where m.id=logs.matter_id and public.lcb_matter_visible(m.data))
);
create policy family_logs_insert on public.logs for insert to authenticated with check(
  exists(select 1 from public.matters m where m.id=logs.matter_id and public.lcb_matter_visible(m.data))
);
create policy family_logs_update on public.logs for update to authenticated
using(exists(select 1 from public.matters m where m.id=logs.matter_id and public.lcb_matter_visible(m.data)))
with check(exists(select 1 from public.matters m where m.id=logs.matter_id and public.lcb_matter_visible(m.data)));
create policy family_logs_delete on public.logs for delete to authenticated using(
  exists(select 1 from public.matters m where m.id=logs.matter_id and (
    public.lcb_app_user_id()='carol' or m.data->>'owner'=public.lcb_app_user_id()
  ))
);

create policy family_meta on public.meta for all to authenticated
using(public.lcb_app_user_id() is not null) with check(public.lcb_app_user_id() is not null);

create policy family_public_keys_read on public.lcb_public_keys for select to authenticated
using(public.lcb_app_user_id() is not null);
create policy family_public_keys_write on public.lcb_public_keys for all to authenticated
using(user_id=public.lcb_app_user_id()) with check(user_id=public.lcb_app_user_id());
create policy family_private_keys on public.lcb_private_keys for all to authenticated
using(user_id=public.lcb_app_user_id()) with check(user_id=public.lcb_app_user_id());
create policy family_matter_keys_read on public.lcb_matter_keys for select to authenticated
using(user_id=public.lcb_app_user_id() or public.lcb_app_user_id()='carol');
create policy family_matter_keys_delete on public.lcb_matter_keys for delete to authenticated using(
  public.lcb_app_user_id()='carol' or exists(
    select 1 from public.matters m
    where m.data->>'id'=lcb_matter_keys.matter_id and m.data->>'owner'=public.lcb_app_user_id()
  )
);

revoke all on public.matters,public.logs,public.meta,public.lcb_public_keys,public.lcb_private_keys,public.lcb_matter_keys from public,anon;
grant select,insert,update,delete on public.matters,public.logs,public.meta,public.lcb_public_keys,public.lcb_private_keys,public.lcb_matter_keys to authenticated;

create or replace function public.lcb_store_wrapped_keys(payload jsonb) returns void
language plpgsql security definer set search_path=public as $$
declare item jsonb; mid text; uid text:=public.lcb_app_user_id(); matter_data jsonb;
begin
  if uid is null then raise exception 'unknown app user'; end if;
  for item in select value from jsonb_array_elements(payload)
  loop
    mid:=item->>'matter_id';
    select data into matter_data from public.matters where data->>'id'=mid limit 1;
    if matter_data is null or not (uid='carol' or matter_data->>'owner'=uid) then
      raise exception 'not allowed to manage matter keys';
    end if;
    if item->>'user_id'<>'carol' and item->>'user_id'<>matter_data->>'owner'
      and not (coalesce(matter_data->'team','[]'::jsonb) ? (item->>'user_id')) then
      raise exception 'invalid key recipient';
    end if;
    insert into public.lcb_matter_keys(matter_id,user_id,wrapped_key)
    values(mid,item->>'user_id',item->>'wrapped_key')
    on conflict(matter_id,user_id) do update set wrapped_key=excluded.wrapped_key;
  end loop;
  for mid in select distinct value->>'matter_id' from jsonb_array_elements(payload)
  loop
    delete from public.lcb_matter_keys k where k.matter_id=mid and k.user_id<>'carol'
      and not exists(select 1 from jsonb_array_elements(payload) p where p->>'matter_id'=mid and p->>'user_id'=k.user_id);
  end loop;
end $$;
revoke all on function public.lcb_store_wrapped_keys(jsonb) from public,anon;
grant execute on function public.lcb_store_wrapped_keys(jsonb) to authenticated;

drop policy if exists carol_files_read on storage.objects;
drop policy if exists carol_files_add on storage.objects;
drop policy if exists carol_files_remove on storage.objects;
drop policy if exists family_files_read on storage.objects;
drop policy if exists family_files_add on storage.objects;
drop policy if exists family_files_remove on storage.objects;
create policy family_files_read on storage.objects for select to authenticated using(
  bucket_id='carol-encrypted-files' and exists(
    select 1 from public.matters m
    where m.data->>'id'=(storage.foldername(name))[1] and public.lcb_matter_visible(m.data)
  )
);
create policy family_files_add on storage.objects for insert to authenticated with check(
  bucket_id='carol-encrypted-files' and exists(
    select 1 from public.matters m
    where m.data->>'id'=(storage.foldername(name))[1] and public.lcb_matter_visible(m.data)
  )
);
create policy family_files_remove on storage.objects for delete to authenticated using(
  bucket_id='carol-encrypted-files' and exists(
    select 1 from public.matters m
    where m.data->>'id'=(storage.foldername(name))[1] and (
      public.lcb_app_user_id()='carol' or m.data->>'owner'=public.lcb_app_user_id()
    )
  )
);

create or replace function public.lcb_register_device_safe(p_device_id text,p_device_name text,p_timezone text) returns void
language plpgsql security definer set search_path=public as $$
declare sid uuid; old_sid uuid; current_ip inet; uid text:=public.lcb_app_user_id();
begin
  sid:=(auth.jwt()->>'session_id')::uuid;
  if uid is null or sid is null or coalesce(p_device_id,'')='' then raise exception 'invalid session'; end if;
  select s.ip into current_ip from auth.sessions s where s.id=sid;
  select d.session_id into old_sid from public.lcb_devices d where d.user_id=uid and d.device_id=p_device_id;
  if old_sid is not null and old_sid<>sid then delete from auth.sessions where id=old_sid; end if;
  insert into public.lcb_devices(session_id,user_id,device_id,device_name,timezone,ip_address)
  values(sid,uid,left(p_device_id,100),left(coalesce(p_device_name,'Unknown device'),120),left(coalesce(p_timezone,'Unknown'),80),current_ip)
  on conflict(user_id,device_id) do update set session_id=excluded.session_id,device_name=excluded.device_name,timezone=excluded.timezone,ip_address=excluded.ip_address,last_seen=now();
end $$;

create or replace function public.lcb_list_devices_safe()
returns table(session_id uuid,user_id text,device_name text,timezone text,city text,ip_address text,created_at timestamptz,last_seen timestamptz,is_current boolean)
language sql security definer set search_path=public as $$
  select d.session_id,d.user_id,d.device_name,d.timezone,null::text,host(d.ip_address),d.created_at,d.last_seen,d.session_id=(auth.jwt()->>'session_id')::uuid
  from public.lcb_devices d join auth.sessions s on s.id=d.session_id
  where d.user_id=public.lcb_app_user_id() order by d.last_seen desc
$$;

create or replace function public.lcb_revoke_device(target_session uuid) returns void
language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from public.lcb_devices where session_id=target_session and user_id=public.lcb_app_user_id()) then
    raise exception 'not allowed';
  end if;
  delete from auth.sessions where id=target_session;
  delete from public.lcb_devices where session_id=target_session;
end $$;
do $$ begin
  if to_regprocedure('public.lcb_register_device(text,text,text,double precision,double precision)') is not null then
    execute 'revoke all on function public.lcb_register_device(text,text,text,double precision,double precision) from public,anon,authenticated';
  end if;
  if to_regprocedure('public.lcb_list_devices()') is not null then
    execute 'revoke all on function public.lcb_list_devices() from public,anon,authenticated';
  end if;
end $$;
revoke all on function public.lcb_register_device_safe(text,text,text),public.lcb_list_devices_safe(),public.lcb_revoke_device(uuid) from public,anon;
grant execute on function public.lcb_register_device_safe(text,text,text),public.lcb_list_devices_safe(),public.lcb_revoke_device(uuid) to authenticated;

create or replace function public.lcb_record_security_event(event_type text,details jsonb default '{}'::jsonb) returns void
language plpgsql security definer set search_path=public as $$
declare uid text:=public.lcb_app_user_id();
begin
  if uid is null then raise exception 'unknown app user'; end if;
  if event_type not in ('login_success','session_expired','sync_failed','backup_exported','backup_restored') then raise exception 'unsupported security event'; end if;
  insert into public.security_events(user_id,event_type,details) values(uid,event_type,coalesce(details,'{}'::jsonb));
end $$;
revoke all on function public.lcb_record_security_event(text,jsonb) from public,anon;
grant execute on function public.lcb_record_security_event(text,jsonb) to authenticated;

create policy family_security_events_read on public.security_events for select to authenticated
using(public.lcb_app_user_id()='carol' or user_id=public.lcb_app_user_id());

commit;
