begin;
create table if not exists public.security_events (
  id bigint generated by default as identity primary key,
  user_id text not null, event_type text not null,
  details jsonb not null default '{}'::jsonb,
  happened_at timestamptz not null default now()
);
alter table public.security_events enable row level security;
revoke all on public.security_events from public, anon, authenticated;
grant select on public.security_events to authenticated;
drop policy if exists carol_security_events_read on public.security_events;
create policy carol_security_events_read on public.security_events for select to authenticated
using (public.carol_personal_user());
create or replace function public.lcb_record_security_event(event_type text, details jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.carol_personal_user() then raise exception 'unknown personal user'; end if;
  if event_type not in ('login_success','session_expired','sync_failed','backup_exported','backup_restored') then raise exception 'unsupported security event'; end if;
  insert into public.security_events(user_id,event_type,details) values('carol',event_type,coalesce(details,'{}'::jsonb));
end $$;
revoke all on function public.lcb_record_security_event(text,jsonb) from public,anon;
grant execute on function public.lcb_record_security_event(text,jsonb) to authenticated;
commit;
